services:
  server:
    container_name: server
    build:
      context: ./packages/server
      dockerfile: Dockerfile.server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HOST=${HOST}
      - SERVER_PORT=${SERVER_PORT}
      # Firebase Admin environment variables
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    env_file:
      - .env
    ports:
      - '3001:3001'
      - '5556:5556'  # Dedicated port for Prisma Studio
    volumes:
      - ./packages/server:/app
      - /app/node_modules
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:${SERVER_PORT}/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 10
    # Use host network mode on Linux to access local PostgreSQL
    # On macOS and Windows, use 'host.docker.internal' in DATABASE_URL instead
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    container_name: client
    build:
      context: ./packages/client
      dockerfile: Dockerfile.client
    depends_on:
      server:
        condition: service_healthy
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - VITE_CLIENT_PORT=${VITE_CLIENT_PORT}
      # Firebase client environment variables
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
    env_file:
      - .env
    ports:
      - '${VITE_CLIENT_PORT}:${VITE_CLIENT_PORT}'
    volumes:
      - ./packages/client/src:/app/src
      - ./packages/client/public:/app/public
      - ./packages/client/index.html:/app/index.html
      - ./packages/client/tsconfig.json:/app/tsconfig.json
      - ./packages/client/tsconfig.node.json:/app/tsconfig.node.json
      - ./packages/client/vite.config.ts:/app/vite.config.ts
      - ./.env:/app/.env
